### ISSUE TITLE
URL with plain IP - missing destination address

### ISSUE THREAD

**Issue by grzech0** [ac000/sprotly#1]
First, it's great piece of software, doing exactly what I need. Its only one transparent https proxy with http upstream, working out of the box. I think I found corner case. It's rare but sometimes appears.

URL using plain IP (expl. https://212.244.48.139/ ) - missing destination address - log looks like that
...
[2023-09-29 10:53:11 +0200] 3475: Proxying 192.168.118.11:52294->[192.168.118.11]:52294
[2023-09-29 10:53:11 +0200] 3475: Closed 192.168.118.11:52294->[192.168.118.11]:52294, bytes tx/rx 848/2471, 95ms
...

for regular FQDN URL (expl. https://ncloud.tunapi.pl/ ) - working properly - log looks like that 
...
[2023-09-29 10:53:08 +0200] 3475: Proxying 192.168.118.11:33032->ncloud.tunapi.pl[192.168.118.11]:33032
[2023-09-29 10:53:08 +0200] 3475: Closed 192.168.118.11:33032->ncloud.tunapi.pl[192.168.118.11]:33032, bytes tx/rx 850/6589, 151ms
...

on client side, using plain IP URL disables SNI field, sprotly should fallback to original destination IP, or I'm wrong here and it's my misunderstanding

**Comment by ac000** [comment]
On Fri, 29 Sep 2023 02:48:10 -0700
grzech0 ***@***.***> wrote:

> First, it's great piece of software, doing exactly what I need. Its only one transparent https proxy with http upstream, working out of the box. I think I found corner case. It's rare but sometimes appears.

Heh, thanks for the report, it's good to know someone is actually using
this thing!

> URL using plain IP (expl. https://212.244.48.139/ ) - missing destination address - log looks like that
> ...
> [2023-09-29 10:53:11 +0200] 3475: Proxying 192.168.118.11:52294->[192.168.118.11]:52294
> [2023-09-29 10:53:11 +0200] 3475: Closed 192.168.118.11:52294->[192.168.118.11]:52294, bytes tx/rx 848/2471, 95ms
> ...

So, I guess you're expecting to see something like

[2023-09-29 10:53:11 +0200] 3475: Proxying 192.168.118.11:52294->212.244.48.139[192.168.118.11]:52294
[2023-09-29 10:53:11 +0200] 3475: Closed 192.168.118.11:52294->212.244.48.139[192.168.118.11]:52294, bytes tx/rx 848/2471, 95ms

> for regular FQDN URL (expl. https://ncloud.tunapi.pl/ ) - working properly - log looks like that 
> ...
> [2023-09-29 10:53:08 +0200] 3475: Proxying 192.168.118.11:33032->ncloud.tunapi.pl[192.168.118.11]:33032
> [2023-09-29 10:53:08 +0200] 3475: Closed 192.168.118.11:33032->ncloud.tunapi.pl[192.168.118.11]:33032, bytes tx/rx 850/6589, 151ms
> ...
> 
> on client side, using plain IP URL disables SNI field, sprotly should fallback to original destination IP, or I'm wrong here and it's my misunderstanding

That sounds right I think...

TBH it's been a few years since I even looked at this. I'll see if I
can set up a test environment and re-familiarise myself with it.

Thanks!
Andrew

**Comment by ac000** [comment]
On Fri, 29 Sep 2023 02:48:10 -0700
grzech0 ***@***.***> wrote:

> URL using plain IP (expl. https://212.244.48.139/ ) - missing destination address - log looks like that
> ...
> [2023-09-29 10:53:11 +0200] 3475: Proxying 192.168.118.11:52294->[192.168.118.11]:52294
> [2023-09-29 10:53:11 +0200] 3475: Closed 192.168.118.11:52294->[192.168.118.11]:52294, bytes tx/rx 848/2471, 95ms
> ...

So to be clear, 192.168.118.11:52294 is the source IP address and port
of the client request.

[192.168.118.11]:52294 is the destination IP address and port

> for regular FQDN URL (expl. https://ncloud.tunapi.pl/ ) - working properly - log looks like that 
> ...
> [2023-09-29 10:53:08 +0200] 3475: Proxying 192.168.118.11:33032->ncloud.tunapi.pl[192.168.118.11]:33032
> [2023-09-29 10:53:08 +0200] 3475: Closed 192.168.118.11:33032->ncloud.tunapi.pl[192.168.118.11]:33032, bytes tx/rx 850/6589, 151ms
> ...

What was 'missing' from the above was ncloud.tunapi.pl which is the
destination hostname, but of course in the above example we didn't have
a hostname.

So that looks right to me...

> on client side, using plain IP URL disables SNI field, sprotly should fallback to original destination IP, or I'm wrong here and it's my misunderstanding

A quick test shows that when we use an IP address that the SNI is blank
and we just use the IP address for the CONNECT.

E.g (some debug output from sprotly) from

curl https://digital-domain.net:1975/

SNI (digital-domain.net)
CONNECT digital-domain.net:443 HTTP/1.0

and curl -k https://[2001:19f0:7402:15d6:5400:3ff:feab:f47a]:1975/

SNI ()
CONNECT [2001:19f0:7402:15d6:5400:3ff:feab:f47a]:443 HTTP/1.0

Sprotly, Squid and curl here are all running on the same host with the
following ip{6,}tables rules

iptables -t nat -A OUTPUT -p tcp -m tcp --dport 1975 -j REDIRECT --to-ports 3129
ip6tables -t nat -A OUTPUT -p tcp -m tcp --dport 1975 -j REDIRECT --to-ports 3129

with sprotly run as

sprotly -D -l :3129 -p :9443

So from my point of view everything is working as expected. But as I
mentioned it's been a long time since I looked at this, it took me a
while to even remember how this was all supposed to work! so it's
quite possible I've missed something.

Fell free to provide some more details if you still think something is
amiss.

Cheers,
Andrew

**Comment by grzech0** [comment]
Here is my testing env

client host (with transparent redirection):
IP: 192.168.118.11

"# route|grep default"
default         192.168.118.1   0.0.0.0         UG    0      0        0 eth0

"# ifconfig  eth0"
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.118.11  netmask 255.255.255.0  broadcast 192.168.118.255

iptables redirect:

"# iptables -L -n -t nat"
...
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:192.168.118.21:3132
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 to:192.168.118.21:3131
DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
...

sprotly host (sprotly, tinyproxy, squid)
IP: 192.168.118.21

"# route |grep default"
default         192.168.118.1   0.0.0.0         UG    0      0        0 eth0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.118.21  netmask 255.255.255.0  broadcast 192.168.118.255

"# netstat -ltupn|grep 31"
tcp        0      0 192.168.118.21:3131     0.0.0.0:*               LISTEN      3474/sprotly        
tcp        0      0 192.168.118.21:3132     0.0.0.0:*               LISTEN      1927/tinyproxy      
tcp6       0      0 :::3128                 :::*                    LISTEN      1572/(squid-1)      
tcp6       0      0 :::3129                 :::*                    LISTEN      1572/(squid-1)

"# ps -ef|grep sprotly"
root      3474     1  0 Sep29 ?        00:00:00 /usr/local/bin/sprotly -l 192.168.118.21:3131 -p 192.168.118.21:3128
sprotly   3475  3474  0 Sep29 ?        00:00:00 sprotly: worker
sprotly   3476  3474  0 Sep29 ?        00:00:00 sprotly: worker

"# cat /etc/squid/squid.conf|grep http_port"
http_port 3128
http_port 3129 intercept


test URL with regular FQDN

on client 
"# curl -Iv https://ncloud.tunapi.pl"
...
< HTTP/2 302 
HTTP/2 302 
< server: nginx
server: nginx
...
< location: https://ncloud.tunapi.pl/login
location: https://ncloud.tunapi.pl/login
...

connection looks OK - got 302


on squid/sprotly system

"# tail -f /var/log/sprotly/access_log"
[2023-09-30 12:43:20 +0200] 3475: Proxying 192.168.118.11:55368->ncloud.tunapi.pl[192.168.118.11]:55368
[2023-09-30 12:43:21 +0200] 3475: Closed 192.168.118.11:55368->ncloud.tunapi.pl[192.168.118.11]:55368, bytes tx/rx 850/6583, 167ms

"# tail -f /var/log/squid/access.log"
1696070601.096    143 192.168.118.21 TCP_TUNNEL/200 6622 CONNECT ncloud.tunapi.pl:443 - HIER_DIRECT/212.244.48.139 -

squid connects to  ncloud.tunapi.pl:443


test URL with plain IP

on client 

"# curl -vI https://212.244.48.139/ -k"
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 212.244.48.139:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 212.244.48.139:443

connection isn't OK - got SSL error

on squid/sprotly system

"# tail -f /var/log/sprotly/access_log"
[2023-09-30 12:45:30 +0200] 3476: Proxying 192.168.118.11:59732->[192.168.118.11]:59732
[2023-09-30 12:45:30 +0200] 3476: Closed 192.168.118.11:59732->[192.168.118.11]:59732, bytes tx/rx 517/0, 28ms

"# tail -f /var/log/squid/access.log"
1696070730.181      1 192.168.118.21 NONE/503 0 CONNECT 192.168.118.11:443 - HIER_NONE/- -


squid tries to connect 192.168.118.11:443 instead of 212.244.48.139:443


I  hope this can explain the case with details You need

Cheers,
Greg

**Comment by ac000** [comment]
On Sat, 30 Sep 2023 04:03:51 -0700
grzech0 ***@***.***> wrote:

> Here is my testing env

Thanks for the info, that's exactly what I needed!

The short of it is I don't think (or at least I can't see at the
moment) that this will work in your current setup.

It's all coming back to me now. The intended use of this was to run on a
GRE/IPSec tunnel endpoint.

This endpoint would have netfilter rules like

  -A PREROUTING -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 3129

The key here is the REDIRECT and that this is happening on the same box
as sprotly.

sprotly uses IP6T_SO_ORIGINAL_DST/SO_ORIGINAL_DST socket options with
getsockopt(2) to get the original destination address of the request.
This is used in the logging and as also as a fallback in the case of no
SNI.

However that only works with REDIRECT and not DNAT. This is why you are
seeing log entries like

> [2023-09-30 12:45:30 +0200] 3476: Proxying 192.168.118.11:59732->[192.168.118.11]:59732
> [2023-09-30 12:45:30 +0200] 3476: Closed 192.168.118.11:59732->[192.168.118.11]:59732, bytes tx/rx 517/0, 28ms

You basically have 192.168.118.11:59732 twice. The second one should
actually be the IP address/port of the actual requested destination.

What you should be seeing is something like

... Proxying 192.168.118.11:59732->[212.244.48.139]:443

As for falling back to the IP address if there is no SNI, sprotly is
indeed trying to do that, though it's possible there;s a bug in there, I
need to find a TLS host that legitimately uses an IP address...

But that won't work anyway due to the DNAT...

Cheers,
Andrew

**Comment by grzech0** [comment]
I forgot how iptables DNAT works. Shame on me. I redesign my testing env - moved sprotly to redirecting machine (192.168.118.11) and URL with plain IP works like charm! 
I run sprotly this way:
root@dev4-20-tunapi:/home/devuan# ps -ef|grep sprotly
root     15092     1  0 10:58 ?        00:00:00 /usr/local/bin/sprotly -l :3131 -p 192.168.118.21:3128
nobody   15093 15092  0 10:58 ?        00:00:00 sprotly: worker
nobody   15094 15092  0 10:58 ?        00:00:00 sprotly: worker

iptables rule looks like that
root@dev4-20-tunapi:/home/devuan# iptables -L -n -t nat
Chain OUTPUT (policy ACCEPT)
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 3131
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:192.168.118.21:3132
DOCKER all -- 0.0.0.0/0 !127.0.0.0/8 ADDRTYPE match dst-type LOCAL

DNAT rule for port 80 still unchanged (yet). I consider moving tinyproxy to redirecting machine and use REDIRECT as well as on 443 port

root@dev4-20-tunapi:/home/devuan# curl -Iv https://212.244.48.139 -k
*   Trying 212.244.48.139:443...
* Connected to 212.244.48.139 (212.244.48.139) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
...

"# tail -f /var/log/sprotly/access_log"
[2023-10-02 11:58:27 +0200] 15094: Proxying 192.168.118.11:57480->[212.244.48.139]:443
[2023-10-02 11:58:27 +0200] 15094: Closed 192.168.118.11:57480->[212.244.48.139]:443, bytes tx/rx 517/0, 34ms

"# tail -f /var/log/squid/access.log"
1696240707.036     11 192.168.118.11 TCP_TUNNEL/200 39 CONNECT 212.244.48.139:443 - HIER_DIRECT/212.244.48.139 -

So...
Thank You for your time
I hope your time wasn't completely wasted. I see you updated the code little bit

**Comment by ac000** [comment]
On Mon, 02 Oct 2023 03:10:23 -0700
grzech0 ***@***.***> wrote:

> I forgot how iptables DNAT works. Shame on me. I redesign my testing env - moved sprotly to redirecting machine (192.168.118.11) and URL with plain IP works like charm! 

Excellent!

[...]

> "# tail -f /var/log/sprotly/access_log"
> [2023-10-02 11:58:27 +0200] 15094: Proxying 192.168.118.11:57480->[212.244.48.139]:443
> [2023-10-02 11:58:27 +0200] 15094: Closed 192.168.118.11:57480->[212.244.48.139]:443, bytes tx/rx 517/0, 34ms

Yeah, that looks better.
 
> "# tail -f /var/log/squid/access.log"
> 1696240707.036     11 192.168.118.11 TCP_TUNNEL/200 39 CONNECT 212.244.48.139:443 - HIER_DIRECT/212.244.48.139 -
> 
> So...
> Thank You for your time

No problem.

> I hope your time wasn't completely wasted. I see you updated the code little bit

No not at all. The code update was for a minor API change in libac, no
need to update, if you do however, you'll also need the current libac.

I'll go ahead and close this off now.

Cheers,
Andrew
